environment:
  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
  QT_VERSION: 5.9.9\msvc2017_64
  VCVARSALLPATH: C:\"Program Files (x86)\Microsoft Visual Studio"\2017\Community\VC\Auxiliary\Build\vcvarsall.bat
  VCVARSALL: x64
  nodejs_version: "12.1.0"
  npm_version: "6.14.4"
  GYP_MSVS_VERSION: 2017
  platform: "x64"

init:
  - call %VCVARSALLPATH% %VCVARSALL%
  - set PATH=C:\Qt\%QT_VERSION%\bin;C:\Qt\Tools\QtCreator\bin;%PATH%;

install:
  - cmd: appveyor-retry powershell Install-Product node $env:nodejs_version x64

build_script:
  - npx @bazel/bazelisk version
  - npx @bazel/bazelisk build //...
  - npx @bazel/bazelisk test //...
  - qmake Quoniam.pro
  - jom

after_build:
  - set ARTIFACT_NAME=%APPVEYOR_REPO_BRANCH%
  - if defined APPVEYOR_REPO_TAG_NAME set ARTIFACT_NAME=%APPVEYOR_REPO_TAG_NAME%
  - 7z a quoniam-%ARTIFACT_NAME%.zip .\bin\*

artifacts:
  - path: quoniam-$(ARTIFACT_NAME).zip
    name: pro build

  - path: .\bazel-bin\src\quoniam-pkg.tar.gz
    name: bazel build
