environment:
  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
init:
  - set QTDIR=C:\Qt\5.9.5\msvc2017_64
  - set PATH=%QTDIR%\bin;C:\Qt\Tools\QtCreator\bin;%PATH%;
build_script:
  - qmake Quoniam.pro
 