config_setting(
    name = "release",
    values = {
        "cpu": "x64",
        "compilation_mode": "opt",
    },
    visibility = ["//visibility:public"],
)

config_setting(
    name = "debug",
    values = {
        "cpu": "x64",
        "compilation_mode": "dbg",
    },
    visibility = ["//visibility:public"],
)
